[build]
  base = "coralin-studio"
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/submit"
  to = "/.netlify/functions/submit"
  status = 200
